name: DevSecOps Security Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:

  # -----------------------
  # 1. TEST JOB (CI)
  # -----------------------
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test


  # -----------------------
  # 2. SAST (SEMGREP)
  # -----------------------
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: |
          docker run --rm -v "${PWD}:/src" returntocorp/semgrep semgrep \
          --config="p/security-audit" /src


  # -----------------------
  # 3. SCA (NPM AUDIT)
  # -----------------------
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run npm audit
        run: npm audit --audit-level=high


  # -----------------------
  # 4. CONTAINER SCAN (TRIVY)
  # -----------------------
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devsecops-lab .

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: devsecops-lab
          format: table
          exit-code: 1
          severity: CRITICAL,HIGH